echo "Test 1: -mC"
python bayesnet.py "-mC"
echo "Test 2: -jcdx"
python bayesnet.py "-jcdx"
echo "Test 3: -j~p~scxd"
python bayesnet.py "-j~p~scxd"
echo "Test 4: -gc|d"
python bayesnet.py "-gc|d"
echo "Test 5: -gc|~dx"
python bayesnet.py "-gc|~dx"
echo "Test 6: Does Not Matter"
python bayesnet.py "-jcDx"
echo "Test 7: -mX"
python bayesnet.py "-mX"
